import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  content: { flex: 1, paddingHorizontal: 24, paddingTop: 0, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 8 },
  subtitle: { fontSize: 15, textAlign: 'center', marginBottom: 50, opacity: 0.8 },
  inputContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, justifyContent:'center' },
  inputBox: {
    width: 50,
    height: 64,
    borderRadius: 12,
    borderWidth: 2,
    fontSize: 28,
    fontWeight: '600',
    marginHorizontal: 4,
    textAlign: 'center',
  },
  separator: { fontSize: 32, fontWeight: '300', marginHorizontal: 6, marginTop: -4 },
  button: {
    width: '100%',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  buttonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  forgotText: { marginTop: 40, fontSize: 14, borderBottomWidth: 1, paddingBottom: 2 },
  content_select: { flex: 1, paddingHorizontal: 24, paddingTop: 40, paddingBottom:30 },
  emptyText: { fontSize: 17, textAlign: 'center', marginTop: 50, opacity: 0.7 },
  list: { flex: 1 },
  cityItem: {
    padding: 18,
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  errorText: {
    color: '#FF3B30',
    fontSize: 15,
    fontWeight: '500',
    marginTop: 15,
    textAlign:'center'
  },
  cityItemSelected: {
    borderWidth: 2,
    borderColor: '#007AFF',
  },
  cityName: { fontSize: 17, fontWeight: '500', flex: 1 },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#999',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  checkmark: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#fff' },
  button_select: {
    width: '100%',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 20,
  },
  buttonActive_select: {},
});